### ISSUE TITLE
Binance Support

### ISSUE THREAD

**Issue by eugjr** [kuegi/kuegiBot#4]
Hello, great stuff you got here, really Nice The topics from Twitter posts.

It's possible to run the bot on backtest and Live on binance futures? 
I'm still New in bot and programming world, but I'm looking for some automations for binance futures, would like to test and understand the básica of your code here.

**Comment by kuegi** [comment]
thx, i am happy if it helps. 
yes. the latest code has full binance-futures support in. I am currently running it on binance myself.
